### ISSUE TITLE
EDTF node in Arches reading from wrong part of the script

### ISSUE THREAD

**Issue by RHVDM** [MAEASaM/Arches-ETL#12]
#### Description
When a date is saved in the edtf node of a resource model (in this case chronology time span of the chronology resource model) the database gives an error related to the collection term not being present. As this is a data node and not a controlled node, the script should not be accessing the collections. 

#### Error message
Unable to save.
ExtendedDateFormat.__init__() got an unexpected keyword argument 'rdmCollection'

#### Files
None

#### To Reproduce
Save any date in an edtf node of a resource model.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Determine why the edtf node script is calling the collections.
- [ ] Task 2
- [ ] Task 3

**Comment by razekmh** [comment]
The issue does not seem to exist on Arches 7.5.2. It is possible that the bug was fixed with the upgrade. We will need access to server log files to track the issue on current server. We will email @dir21 about this. I suspect we already have the password but we just do not know where to find it

**Comment by RHVDM** [comment]
Deleting the entire model (including the main branch) and rebuilding it has solved this problem. In the EDTF date can now be saved.
